services:
  kbs_postgresql:
    container_name: kbs-database
    image: postgres:13.3
    ports:
      - '49171:5432'
    volumes:
      - ./docker/data/postgresql:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - kbs_ntwrk

  kbs_kafka:
    container_name: kbs-kafka
    image: bitnami/kafka:3.6
    volumes:
      - ./docker/data/kafka:/bitnami/kafka
    user: root:root
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_KRAFT_CLUSTER_ID=${KAFKA_KRAFT_CLUSTER_ID}
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://10.12.0.7:9092
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kbs-kafka:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      kbs_ntwrk:
        ipv4_address: 10.12.0.7

volumes:
  kbs_postgresql:
  kbs_kafka:

networks:
  kbs_ntwrk:
    driver: bridge
    ipam:
      config:
        - subnet: 10.12.0.0/16
          gateway: 10.12.0.1